### ISSUE TITLE
Improvements for skycoin Docker containers

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1190]
Run integration tests ( [Docker Cloud](https://docs.docker.com/docker-cloud/builds/automated-testing/) ? ) prior to publishing containers onto Docker Hub .

**Comment by olemis** [comment]
Other references
https://alexei-led.github.io/post/docker_testing/
https://saucelabs.com/blog/devising-a-testing-strategy-for-containers

**Comment by gz-c** [comment]
go1.10 is fine and we will upgrade go as new releases come out

**Comment by gz-c** [comment]
note the last step for the dev image is not priority

**Comment by stdevMauricio** [comment]
I just fixed an old problem with the travis tests. The tests used to fail on forks, because the command `go get -t ./...` expected the code to be in $GOPATH/src/github.com/skycoin/skycoin, and it goes to $GOPATH/src/github.com/$FORK/skycoin by default. Just cloning it by hand and checking to the right commit solves all the problems and the tests pass.

**Comment by olemis** [comment]
@gz-c why was this reopened ? Any issues detected ?

**Comment by olemis** [comment]
replying to self => some task list items not covered by PR #1234 .

**Comment by olemis** [comment]
Testing and continuous integration of Docker containers will be done in a separate issue, see #1433

**Comment by stdevMauricio** [comment]
I'm making a README for the mainnet Dockerfile. Should I move all the Docker instructions (run and build) to this README or just the build instructions?
