### ISSUE TITLE
POST /wallet/transaction uses more inputs than necessary

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1428]
Doing some tests, the following happened:

When trying to send 5 coins from a a wallet with multiple addresses, `/wallet/transaction` returned this transaction (it has no problems):
![tx1](https://user-images.githubusercontent.com/34079003/39601872-70181088-4ef1-11e8-92d7-fe21ca402e7b.png)

By changing the amount of coins to 5.999, the normal thing would be to have same inputs and only one output. However, `/wallet/transaction` returned this transaction:
![tx2](https://user-images.githubusercontent.com/34079003/39602116-354908ee-4ef2-11e8-9a0d-02cb415cb3f7.png)

The last input is unnecessary. The two coins of the las input are returned to the wallet and 50% of its hours are unnecessarily burned.

Additionally, the hours are not evenly distributed, but the wallet sends `"share_factor": "0.5"`.

**Comment by therealssj** [comment]
thats how its supposed to be because overall we are preserving hours
427 + 242 = 669
Burn = 335
Remaining = 334
Now we sent 334 / 2 = 167 to receiver
We are left with 167, what do we with them?
If we send them to receiver we lose another 167 hours! (this is how it worked before)
Now what we do is 
Select another output, in above case one with 215 hours
Burn = floor(215 / 2) = 107
Remaining = 108

Now we can send the above 167 hours to the last input 
So instead of burning 167 hours we burned 107!

Our goal here is to make this beneficial for the sender

**Comment by Senyoret1** [comment]
Oh, I didn't know it was by design :sweat_smile:
