### ISSUE TITLE
Use golang:1.10.2-alpine as base image for dockerfile

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1429]
... considering that [Docker Cloud vulnerability reports](https://hub.docker.com/r/library/golang/tags/) say it's less susceptible to known vulnerabilities.

**Comment by stdevMauricio** [comment]
The vulnerabilities do not affect the final skycoin image, because the golang image is used just to compile the code. The final image is actually based on alpine:3.7, I just copy the compiled code from the vulnerable one. The code never runs on a vulnerable image.

**Comment by stdevMauricio** [comment]
We are using the non-alpine version just to compile skycoin and it is discarded when all the binaries are copied to the minimal alpine image. That's why the final image is so small (25MB). The golang:1.10 image is 301MB and is only needed because it comes with all the necessary tools to build the source code.

**Comment by olemis** [comment]
No need to take a look into this since `golang` Docker images are not used as base for `skycoin/skycoin` .
