### ISSUE TITLE
(Wallet) Select style in the send coins page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1446]
The select control on the send coins page does not show the arrow on the right side and does not show a text asking the user to choose an option. I think it would be better to remove `-webkit-appearance: none;` from it and put an initial text like the one in the web wallet:

![drop](https://user-images.githubusercontent.com/34079003/39728105-69d38506-5223-11e8-81ae-dac82e970b9d.png)

**Comment by mahansky** [comment]
`skycoin-web` has placeholders only in this form, `skycoin` nowhere. Do you think they should be added now? I think we already discussed it which ended by not adding them.

Since the default 'arrow' is inconsistent across browsers/os, I tried chevron icon from wallets page and that looks pretty good  
![screen shot 2018-05-08 at 15 38 35](https://user-images.githubusercontent.com/1536298/39760562-e69791ec-52d5-11e8-8ce2-c555c448e0a4.png)

**Comment by Senyoret1** [comment]
If there was already a discussion about placeholders, then I guess it's better to leave the control as it is. About the icon, I also think it looks pretty good, it would be good to add it.
