### ISSUE TITLE
API endpoints to create unsigned transaction from unspent outputs

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1461]
https://github.com/skycoin/skycoin-web/pull/100

External wallets such as the web wallet have to implement unspent output selection themselves.  The mechanism of unspent output selection can become complicated, it would be better and safer to provide an API to do this.

The API would accept a set of unspent outputs and construct an unsigned transaction based upon other parameters. The other parameters would be similar to /wallet/spend.  

#1460 should probably be done first, to get the code for outputs sorted out.

**Comment by Senyoret1** [comment]
Probably an endpoint that directly creates the transaction would be more appropriate. If the complete transaction is returned, it would be easier for external wallets to automatically comply with any change in the rules, such as a possible reduction in the percentage of hours that should be burned or a change that has not yet been considered, as in https://github.com/skycoin/skycoin/issues/1421. Additionally, returning only the outputs would still left unattended some relatively complicated details (which could open the door to errors due to poor implementation), such as when an additional input is used to be able to return some hours to the user in a new output, as explained here: https://github.com/skycoin/skycoin/issues/1428.

**Comment by gz-c** [comment]
Ok, this endpoint should also return the outputs that should be created.

It can't create a transaction because the transaction needs to be signed, the final assembly must be done externally

**Comment by Senyoret1** [comment]
Ok, the inputs and the outputs should be sufficient. The rest can be done with relative ease.

**Comment by gz-c** [comment]
This should possibly be done as an endpoint to create an unsigned transaction (#1513), if we also need to return the outputs to create as well.  The difference being that for the web wallet use case, there is no internal wallet to reference and all outputs must be provided.  This means that we may have two endpoints to create an unsigned transaction: one that uses the internal wallet, and another that doesn't.  The only difference being that the former can specify a wallet to spend from and the latter cannot.

**Comment by gz-c** [comment]
Formerly the title included "sign unsigned transaction" - however it is decided not to have an API which accepts secret keys as inputs. Signing should always be done locally.  `POST /api/v2/wallet/transaction/sign` can sign from a given wallet.  Languages other than go can use github.com/skycoin/skycoin-lite or github.com/skycoin/libskycoin for bindings to the signing code to sign locally.
