### ISSUE TITLE
Tool for genesis coin distribution

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1468]
Generally the steps involved in distribution of coins are: 

1. Generate `n` distribution addresses, preferably `100` and substitute them here https://github.com/skycoin/skycoin/blob/develop/src/visor/distribution.go#L95

2. uncomment this code https://github.com/skycoin/skycoin/blob/71d24a0fe6d16e2a4ccb6833c0d0734c60b468e6/cmd/skycoin/skycoin.go#L799-L804 and set the genesis address secret key here

3. comment out the following lines https://github.com/skycoin/skycoin/blob/94523128669bab20389b558711f26b61dbc0c927/cmd/skycoin/skycoin.go#L791-L794

4. uncomment this https://github.com/skycoin/skycoin/blob/71d24a0fe6d16e2a4ccb6833c0d0734c60b468e6/cmd/skycoin/skycoin.go#L724-L732 and replace with
    ```
    time.Sleep(5)
    tx := InitTransaction()
    _, _, err = d.Visor.InjectTransaction(tx)
    if err != nil {
        log.Panic(err)
    }
   ```
5. Run the node to make the distribution transaction
6. Comment out the distribution code( make sure to remove the `seckey` 

## Task
- create a cli tool to use the `seckey` and send out the genesis coins to `100` random addresses, store the seeds of those addresses in a text file.

Steps:
1. get address of genesis block from seckey 
2. get uxid of that address
3. build a transaction with 100 outputs
4. inject the transaction

**Comment by gz-c** [comment]
The setup script for the blockchain should be something like this:

Inputs:  seed, initial number of coins, number of address to split to [number of coins must be perfectly divisble by number of addresses]

Generate random master pub,sec key used for signing the genesis block
Generate random genesis pub,sec,addr key 
Create a genesis block with initial number of coins send to genesis address, sign it, add to blockchain

Using the seed, generate N pub,sec,address pairs
Generate another random master pub,sec key used for signing other blocks
Create a transaction that splits the genesis block coins amongst N addresses, sign it, add to blockchain

Print the 2nd master pub,sec key pair as hex
Print the genesis address, the signature and the timestamp of the genesis block

The two different signing keys may not be necessary, if not, use one pair.

**Comment by olemis** [comment]
related to #828 and #988

**Comment by nutmix** [comment]
If the creation script is to generate the n distribution addresses, it should also output a file with the secret keys.  The coin owner (Who runs the script) will then remove these and store them securely for later use.  Personally, I would write the distribution public keys to a configuration file, which is then read by the master node to do the required locking  (usually 75%).  However, currently, these are hard coded in distribution.go as mentioned above.

**Comment by nutmix** [comment]
Should the script check that another coin is not already using the given port, and that a genesis block already exists, and that the distribution accounts were not already done as a failsafe?  I would do each check before that stage, so that you could re-ruin the script if needed.

**Comment by therealssj** [comment]
we can have a template file for `distribution.go` as well in which we will just replace the distribution addresses read from a config file.
I am in favour of having them hardcoded as well


Regarding ports, I am not sure, should we maintain a list somewhere on what ports are already used?then the script can fetch that and do the checks

The check for  genesis should already be in the files, there is the function `maybeCreateGenesisBlock` which creates the genesis block and I assume it already does the check. Need to look into it further

**Comment by nutmix** [comment]
"Regarding ports, I am not sure, should we maintain a list somewhere on what ports are already used?then the script can fetch that and do the checks"

Agreed we need a central list.  This is currently maintained by one of the skycoin team (not sure his github handle), but gz-c has the current list.  Its an good idea to make this list of assigned ports public - e.g. on github.  Some coins may prefer to be anonymous, but they can still have their ports blocked out.

I suggest it may be a good idea to make sure that someone doesn't accidentally create a new coin (using our new coin creation scripts) with an existing coins port, e.g. because they forgot to change it or didnt know.  The best way to do this currently is to try to connect to it.  However, if there is no consequence to doing this (no errors or conflicts) then lets not bother.

Interestingly, developers will be creating their own test version of coins, and will not register.  Usually they will  not be creating their blockchains on a server without publicly accessible ports.  They may try to use the same ports as their main coins.  The question is, should we allow this?

We could also block out a port for each coin for an optional public test net, e.g. one below the main net.
