### ISSUE TITLE
Support omitempty flag for encoder struct tag

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1576]

**Comment by olemis** [comment]
This is hard to implement . Not for encoding , but for decoding . The later works by keeping a go lang type in context and binding the __field__ in order to next byte in buffer . When parsing the bytes stream how to know whether you have to skip current type field due to it been omitted while encoding vs using it to parse next byte?

**Comment by gz-c** [comment]
@olemis it can only work for the final field in a struct

**Comment by olemis** [comment]
@gz-c sure , that's the only exception
