### ISSUE TITLE
Wallet address order is inconsistent when generating addresses

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1583]
Don't know if this is a UI issue or backend issue, but after creating a new wallet then manually adding addresses, the new addresses are inserted in a non-appending order.

**Comment by gz-c** [comment]
This appears to be a frontend issue; `/api/v1/wallet?id=...` returns the addresses in the correct order

**Comment by Senyoret1** [comment]
`/api/v1/wallet?id=...` returns the addresses in the correct order, but `/api/v1/wallet/balance?id=...` does not. The solution could be to modify `/api/v1/wallet/balance?id=...` so that it returns the addresses in the correct order or modify this function so that the order returned by `/api/v1/wallet/balance?id=...` is always used:
https://github.com/skycoin/skycoin/blob/8d71b3c729b13a422154c42879a8cfd48de947f3/src/gui/static/src/app/services/wallet.service.ts#L236-L248

**Comment by therealssj** [comment]
`/api/v1/wallet/balance?id=...` returns a map and they are unordered 
best would be to modify the frontend

**Comment by gz-c** [comment]
The API returns a map so the order can't be controlled.  The API would need to return an array instead.

The frontend will need to maintain the order.
