### ISSUE TITLE
The address will be shown in the next wallet item after shrinking

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1727]
![image](https://user-images.githubusercontent.com/2589926/43046817-e001b962-8e11-11e8-8d91-20e0a7902cd0.png)

**Comment by Senyoret1** [comment]
I think that since the new design was implemented the wallet only works well if the window width is 992px or more. Using an smaller width in version 0.23 does this:
![23](https://user-images.githubusercontent.com/34079003/43074374-01fcd57c-8e4b-11e8-8e69-3f59cc26832e.png)

In the web wallet some improvements were made to make it work well stating from 768px (for a smaller width it would be necessary to make much deeper changes to the design): https://github.com/skycoin/skycoin-web/pull/435

Would it be appropriate to include similar changes in 0.24?

**Comment by gz-c** [comment]
Is it fine in the default size of the electron window?  If its a lot of work to correct this, we will not do it for v24
