### ISSUE TITLE
Security:  CSRF token what's the point !?

### ISSUE THREAD

**Issue by mpsido** [skycoin/skycoin#1731]
The wallet do not accept any request if the CURL request do not provide a "fresh" (less than 30 seconds old) CSRF token.
That is a fine idea in theory, but what's the point if getting a token works without any authentication:
Just like this:
curl -X GET http://127.0.0.1:6420/csrf

Here is a python script that creates a wallet (could do the same with transaction signing...)

    import requests
    import json

    r = requests.get("http://127.0.0.1:6420/csrf")
    token = json.loads(r.content.decode('utf-8'))['csrf_token']

    url = 'http://127.0.0.1:6420/api/v1/wallet/create'
    headers = {'X-CSRF-Token': token }
    # seed = "cloud flower upset remain green metal below cup stem infant art thank"
    seed = "upset flower kitchen virus denial novel yard million smile cube knee image"
    data = { 'seed':seed, 
            'label':"curl_wallet" , 
            'scan':5 , 
            'useEmulatorWallet':"true" }

    p = requests.post(url, headers=headers, data=data)

**Comment by gz-c** [comment]
CSRF is meaningless outside of the browser (e.g. when using curl).  You can disable the CSRF token with CLI parameters if you are not using the browser to communicate with the API.  Although if you run a browser at all on the same machine as the daemon, your wallet is at risk.

**Comment by mpsido** [comment]
What sort of attack does this token protects againsts that cannot be fixed with just one extra token request.

**Comment by gz-c** [comment]
When CORS is enabled, a malicious website cannot obtain a CSRF token from the API.  CORS will prevent the website from reading the response.  

However, the request is still processed by the daemon.  This means that APIs which modify data (such as `/spend`) are at risk to attack. The attacker makes a malicious request, which is processed. Then, due to CORS, it cannot read the response. But in this case, the response does not matter, the attack has already finished.

By using a CSRF token, the CORS protection of `POST` endpoints is complete.

**Comment by mpsido** [comment]
I will read more about that, it is too recent for me.
Does it forbid to get answer if the malicious page was sent to client with a Allow-Cross-Domain-Request='*' ?
