### ISSUE TITLE
Replace Github API version check with a skycoin.net domain check

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2043]
The frontend makes a request to the github API to get the repo version tags in order to detect version upgrades and provide a new client version notice.

Replace this with a request to some file on a skycoin.net domain.

Update the electron domain whitelist to remove the github API domain.

The CSP should be configured to prevent data exfiltration through other domains.

This requires which skycoin.net url to be defined first.

**Comment by Senyoret1** [comment]
The URL can point to a simple text file with the version number, nothing very sophisticated is necessary. However, it is important to keep in mind that the whitelist contains host names and ports, so if the file is added in `www.skycoin.net` the application will have access to all the content on that domain, so if the goal is to be very cautious it would be best to add the file in a subdomain.

**Comment by gz-c** [comment]
We will use `version.skycoin.net`

**Comment by Senyoret1** [comment]
It would probably be good to use a more generic name, just in case it is necessary to add more information in the future, like the USD price or something else.

**Comment by Senyoret1** [comment]
Taking into account the discussions we have had about the hardware wallet, it would be good to use this new subdomain to publish the hw wallet firmware file and the info about the lastest version.

At least from my point of view, nothing fancy is needed. I think we just need an URL (like data.skycoin.net/hw.json) to get a json file with the current version number. Also, the firmware file must be uploaded with a predictable name. For example, if the latest version is "1.0.1", then the firmware file should have a name like "hw-1.0.1.bin", or something like that, so that the desktop wallet can "guess" what the name of the firmware file is.

**Comment by gz-c** [comment]
`version.skycoin.net` will have version data files,
`downloads.skycoin.net` will have the firmware files,
is that ok?

**Comment by Senyoret1** [comment]
That should work. Uploading the information to different subdomains should not cause problems, what is really important is to have access to the version number and the firmware file.

**Comment by gz-c** [comment]
The desktop wallet version file is now available at https://version.skycoin.net/skycoin/version.txt

It may or may not have a newline added, which should be ignored.  The version follows the semver format, so you can use a semver parser to parse and compare version strings correctly

**Comment by Senyoret1** [comment]
@gz-c I tried to use that url, but there is a problem with cors policy:
![cors](https://user-images.githubusercontent.com/34079003/58738459-d7995880-83d3-11e9-8b61-bfba66b29b1d.png)

**Comment by gz-c** [comment]
I'll need to setup a CORS policy on that bucket

**Comment by gz-c** [comment]
@Senyoret1 the CORS policy is set up, it should work now
