### ISSUE TITLE
Show coin hours info in the transaction history page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2092]
Show the number of coin hours sent/received/burned etc in the transaction history page

**Comment by benji241** [comment]
This would be very handy!

**Comment by Senyoret1** [comment]
Probably the most complicated part of this would be to properly manage the space. One option could be to place the values below the addresses:

![2](https://user-images.githubusercontent.com/34079003/51505244-df107b80-1dbb-11e9-9b17-cd260b73e764.png)

Another option would be to omit the burned hours and only show the value that is most relevant for the user (all hours lost, in case of sending, or all hours received, otherwise):

![1_0](https://user-images.githubusercontent.com/34079003/51505247-eafc3d80-1dbb-11e9-8ff9-37211743a6dc.png)

Burned hours could be displayed in a tooltip:

![1_1](https://user-images.githubusercontent.com/34079003/51505250-edf72e00-1dbb-11e9-9c54-9e382bdaad1e.png)
![1_2](https://user-images.githubusercontent.com/34079003/51505253-f2234b80-1dbb-11e9-9091-45433e06e469.png)

**Comment by gz-c** [comment]
What about displaying all info on the right side, without a tooltip?

**Comment by gz-c** [comment]
@mahansky do you have any suggestions

**Comment by mahansky** [comment]
I would go with the second option - show only the relevant thing to the user and leave the rest to the transaction detail modal that shows up when you click on a transaction.

**Comment by gz-c** [comment]
We could keep a symbolic representation on the right side but use other indicators:

* `-` can be used for total lost
* 🔥 (`&#x1f525;`) can be used for burned
* ⇉ or some other unicode arrow can be used for sent

The last two can be grey, to indicate they are a lesser value

**Comment by Senyoret1** [comment]
The problem is that too much vertical space would be used. I think that if there is only one address involved the amount of wasted space is very noticeable, and that so much information would make it more complicated to find the desired transaction at a glance while scrolling:
![test](https://user-images.githubusercontent.com/34079003/52249615-6684e100-28ca-11e9-949f-570a89b1ad47.png)
