### ISSUE TITLE
Send cancel command on X press

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#2238]
Send `cancel` operation on press of `X` otherwise the user has to take the wallet out and put in again before continuing 

<img width="473" alt="Screenshot 2019-03-20 at 6 46 44 AM" src="https://user-images.githubusercontent.com/8619106/54652207-0d6cb780-4adc-11e9-84d4-6423848c0433.png">

**Comment by Senyoret1** [comment]
It should already be working that way, at least it does in my tests. Is the problem happening in a specific place?

**Comment by therealssj** [comment]
In the restore backup procedure it doesnt work on any screen.

**Comment by Senyoret1** [comment]
As the image in the original message shows the modal window in which the user must write the word requested by the device, I tested that part (with various versions of the firmware and the desktop wallet) and I could not find the problem, by pressing the X the process was always canceled. I also tested the need to reconnect the wallet, because when starting the operation the function to cancel the last operation is called, so it should not be necessary to reconnect the device, and everything seems to be working as intended.

However, I found that by pressing the X when the user is told to confirm the recovering operation on the device the operation is not canceled (in fact the error is that the X button should not be visible in that case), as well as something similar when the seed is generated automatically.

I fixed those errors in https://github.com/skycoin/skycoin/pull/2239, but that PR does not change anything about the X button in other windows, because I could not find the error elsewhere. Could you please check again if the error is appearing to you elsewhere?
