### ISSUE TITLE
Swaplab "buy skycoin" button is grey

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2316]
<img width="738" alt="Screen Shot 2019-05-14 at 2 06 47 PM" src="https://user-images.githubusercontent.com/26845312/57674331-96721c00-7651-11e9-9712-a2b70da82cbb.png">

**Comment by mahansky** [comment]
As every other, non-selected button. We could make it a bit less transparent.

**Comment by Senyoret1** [comment]
It is for consistency. The element making the button look different is the color of the icon, but, as @mahansky said, we could make it a bit less transparent if you think it would be appropriate.

**Comment by gz-c** [comment]
I see, it is consistent with the other buttons. Can we move it to the left side with the other buttons?  If not, then make it more visible.

**Comment by Senyoret1** [comment]
Those changes would be very simple. Here are the results.

Current state:
![ri1](https://user-images.githubusercontent.com/34079003/57818877-fb159f80-7753-11e9-99ea-bedb925fe7c5.png)

Current one with less transparency (the change is subtle so that it does not clash with the current style):
![ri2](https://user-images.githubusercontent.com/34079003/57818950-30ba8880-7754-11e9-8618-5aed65a29b9a.png)

Moved to the left:
![lf1](https://user-images.githubusercontent.com/34079003/57818967-42039500-7754-11e9-9bde-5b9ce7ac0dba.png)

Moved and with an black icon:
![lf2](https://user-images.githubusercontent.com/34079003/57818980-5182de00-7754-11e9-935e-9cf1fb64838d.png)

In my opinion, the second option (current one with less transparency) is the best, as adding the button at the right makes it clear to the user that it is a special section.

**Comment by Senyoret1** [comment]
Asking for feedback, @gz-c @mahansky

**Comment by gz-c** [comment]
I like the 4th one.  What about, "Buy Skycoin" to the right but with no transparency?

**Comment by Senyoret1** [comment]
If you ask me, placing the button to the right and without transparency is a risky decision, it could confuse some new users (the current ones probably would not have problems) about which section is currently selected, and it would also make it more difficult to implement the effect of highlighting the button when the cursor is on top of it, currently present on the web wallet:
![ri3](https://user-images.githubusercontent.com/34079003/57872362-85541700-77d9-11e9-8b1e-e9cca9bf3c9a.png)

As this should be done soon, I implement option 4 in https://github.com/skycoin/skycoin/pull/2332, so you can add  the change quickly simply by merging that PR. However, if you want some other change, it can be done.

**Comment by mahansky** [comment]
I think it makes sense to have it on the right. I would probably stick with what we have + less transparency. (Senyoret's example n. 2)
![img2](https://user-images.githubusercontent.com/34079003/57818950-30ba8880-7754-11e9-8618-5aed65a29b9a.png)
If the buy button needs to be a bit more prominent, maybe no transparency + black and yellow image as the difference between normal and selected option?

**Comment by gz-c** [comment]
OK we can leave it as is
