### ISSUE TITLE
Swaplab does not load 

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2317]
<img width="1120" alt="Screen Shot 2019-05-14 at 2 08 22 PM" src="https://user-images.githubusercontent.com/26845312/57674401-ca4d4180-7651-11e9-8ef6-14cf38713439.png">

**Comment by mahansky** [comment]
It's a problem on their side. You can't change which coin you want to trade on their website either https://swaplab.cc/ (sometimes it works)

**Comment by Senyoret1** [comment]
Maybe it will work again after Binance deposits and withdrawals are reactivated.

**Comment by gz-c** [comment]
How can I switch to the swaplab sandbox?

**Comment by mahansky** [comment]
By running the frontend in dev mode: `npm run start` from `skycoin/src/gui/static`

**Comment by Senyoret1** [comment]
The problem is that the sandbox won't make it work. The sandbox only has methods to create and verify transactions (https://swaplab.cc/api-v3-skycoin/index.html#sandbox-methods), not to obtain the list of available pairs, for getting that info we have to use the normal production method, the one that is not working.

**Comment by gz-c** [comment]
Swaplab is back on
