### ISSUE TITLE
Simple procedure for deploying a public API node with HTTPS

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2361]
Something like, nginx+docker+letsencrypt

**Comment by iketheadore** [comment]
Let's encrypt can't issue certificates to bare IP addresses, so before deploying a public node, we must have a domain and create a DNS record to bind the server ip address.

After checking and testing, I found it could be too complicate to deploy a public API node with nginx+docker+letsencrypt. Check https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx and https://devsidestory.com/lets-encrypt-with-docker/, both show the steps and too complicate. 

In contrast, it's easer to deploy with `traefik`, we're using it in our k8s as proxy too. I did a test and it worked good. Traefik would handle the letsencrypt things automatically, what we need to do is create a traefik config file and a docker compose file. Then run `docker-compose up`, a safe public api node will be created. 

To make the config steps easer, we can create or add a cli command, so that user don't have to manually create and config the files. I did a demo cli, with it, we can deploy a public api node by running  `cli run --email example.com@gmail.com --host testnode.example.com`.

**Comment by gz-c** [comment]
I had put letsencrypt in the teller daemon, I assumed it could be used similarly with an nginx plugin

**Comment by gz-c** [comment]
Anyway, the goal is to create the easiest method to deploy a public API node with HTTPS, any method is ok

**Comment by BigOokie** [comment]
The following may be helpful

I have seen this used on several other projects:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

Usage:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage

This is an overview of how it’s used with another project:
https://metamost.com/ghost-docker-setup/amp/

The BTCPay project also uses this method I believe.

**Comment by BigOokie** [comment]
I will follow the steps outlined here and report back if I can successfully get a Skycoin Node running with HTTPS using this method. 
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Advanced-usage

Steps 1-3 appear “standard” with step 4 being where we would spin up the Skycoin container.

If this works, should be possible to create a Docker compose file that will standardise and simply the end-user process.

**Comment by BigOokie** [comment]
I will also (time permitting) take a look at [Caddy Server](https://caddyserver.com/) which looks promising.. testing needed.

**Comment by BigOokie** [comment]
I've successfully tested and now deployed a Skycoin Node and exposed its API behind Cloudflare and Caddy Server.

Its not mandatory to deploy behind Cloudflare - however this can be useful if you want to server your domains from their IP addresses and also use their other services to help safe guard your server.

The below process assumes the domain you are serving is setup and managed in Cloudflare.

You also need to download Caddy Server. Use the download facility they provide to generate an self-installing URL and simply paste that into your server terminal. Make sure you include the Cloudflare DNS plugin.

Once Caddy Server is installed on your server you need to create a `Caddyfile` (capitalisation is important as follows:
```
node.domain.com {
   tls {
      dns cloudflare
   }
   proxy / xxx.xxx.xxx.xxx:6420 {
      transparent
   }
}
```

Replace `node.domain.com` with your actual domain you want to publicly host the node on.
Replace the `xxx.xxx.xxx.xxx` with the  IP address of the private server where your Skycoin Node is running. I also assume Skycoin Node API is exposed on the default port `6420`.

You (may) need to alter firewall rules to forward traffic for ports `80` (http) and `443` (HTTPS) to your Caddy Server.

If using Cloudflare (as per this example) you will need to configure 2 environment variables on your Caddy Server:
```
export CLOUDFLARE_EMAIL=your@email.com
export CLOUDFLARE_API_KEY=yourverylargerandomapikeythatcloudflareprovide
```

You will need to get the values for these from your Cloudflare dashboard.

Run `caddy` in the same folder where your `Caddyfile` configuration file is located and `caddy` will pickup the config automatically from there.

`caddy` will obtain an SSL certificate for you from LetsEncrypt for the domain you are hosting through it. If you followed the above - this should all work ok.

**Comment by BigOokie** [comment]
@iketheadore Not sure if you're still working on this. You are listed as assigned. The above process has worked for me. Let me know if you want any further details.
