### ISSUE TITLE
Loading a wallet from backup seed does not work

### ISSUE THREAD

**Issue by Retsediv** [skycoin/skycoin#2470]
I can not load a wallet from backup seed by using skywallet electron application(build from 
https://github.com/skycoin/skycoin/commit/bde6df2b71bc8997bef93c3e4098565cf44a406b commit) 

It stuck on the following screen:
![image](https://user-images.githubusercontent.com/10120566/61899055-55d13180-af23-11e9-94a7-25758bc61535.png)
![image](https://user-images.githubusercontent.com/10120566/61899063-5964b880-af23-11e9-8372-dac311eb1858.png)

The interesting fact, that it's working correctly with the previous version(which is located on skycoin.org webpage) 
I tried to do this with running daemon and not. 

Environment: Linux Mint 19.1

**Comment by Senyoret1** [comment]
The problem is that the precompiled version of the GUI that is included in the repo is outdated. For it to work, you have to recompile the front-end first or use a precompiled version I added in https://github.com/skycoin/skycoin/pull/2471


For using the version included in the PR simply call this on the root folder of the repo:

```
git fetch origin pull/2471/head:pr2471
git checkout pr2471
./run-client.sh
```

(if you cloned the repo directly instead of using a fork, you may have to replace `origin` with `upstream`)

You can also recompile the Electron version after that, if you want.
