### ISSUE TITLE
Do research about the prometheus client package

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2561]
Consider to replace the current prometheus package to collect metrics. Because the current package's dependencies are too big, consider to find a lighter one. 

Options to consider:
- https://github.com/VictoriaMetrics/metrics

**Comment by jdknives** [comment]
@iketheadore I reached out to their support and it turns out that their client package you linked only supports two types of metrics if used with a Prometheus server:

- counter
- gauge

That means histograms often used for request durations for instance will only work with their own server. So if we wanted to switch to Victoria, we also need to use their server imo.
