### ISSUE TITLE
Make the number easier to read

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2602]
Requested by Synth:

When typing numbers in wallet, like 10 000.

Can we put a slight space, every 3 digits to make it easier to read number, and make it easier to see difference between 10,000 and 100,000

or put an implicit comma, that the user doesn't type and which is not in the text field

**Comment by iketheadore** [comment]
Hi @Senyoret1 would you mind to handle this when you got time, thanks.

**Comment by Senyoret1** [comment]
Sorry for the delay. Fixed in https://github.com/skycoin/skycoin/pull/2616

However, I think another problem is that it is nor very easy to see the decimal values in the UI. Maybe it would be good to use a different style for the decimal parts. Instead of this:
![v1](https://user-images.githubusercontent.com/34079003/120038030-9ba02a80-bfd0-11eb-8e2e-cf4167edb962.png)
we could show something like this: 
![v2](https://user-images.githubusercontent.com/34079003/120038042-a2c73880-bfd0-11eb-853a-6b22ea6ab0c8.png)
The explorer would also need something similar. What do you think?

**Comment by iketheadore** [comment]
I agree, the second one looks better.

**Comment by iketheadore** [comment]
Hi @Senyoret1 , I checked the code and had a test on local env. All looks good, except that some of the decimal values are not processed, also when coins value is not big, such as 
![image](https://user-images.githubusercontent.com/2589926/123899916-74f85980-d9ab-11eb-90d3-10f9a4407e82.png)
, the different style of the decimal value would look a little weird. So perhaps we should keep the old style.

**Comment by Senyoret1** [comment]
I didn’t use the new format in the USD values, but I can use it in them if you want. Appart from that, did you found other coin values not using the new format?

About the format in small numbers, I was also thinking about that while making the PR but found 2 things.

The first one is that using the new format only for some values would make the UI appear to be inconsistent, as the user don’t have to kanow the rules used by the system for deciding when to show small decimals and when not. The use of the 2 formats in the same place at different times could appear to the users just like erratic behavior.

The other thing is that the change made in this PR should be for practical reasons and not really for aesthetic reasons, so in the case of “1.234” it still serves for quickly identify that the value is not more than one thousand, because the point is very small. Also, in a lot of regions the thousands are separated using points and the decimals with a comma, which is just the contrary of the format used in the US, and that could make the numbers even more confusing for some users.

These are the reasons for the current behavior, but if you still want changes to be made, just tell me.
