### ISSUE TITLE
What's the scaling strategy for the sky blockchain?

### ISSUE THREAD

**Issue by steadyclackin** [skycoin/skycoin#903]
I understand that with sky ledger there can be any number of distinct blockchains, and this will ameliorate the tps limits a bit, but what's the roadmap for scaling a single blockchain? The TON Technical Whitepaper outlines an elegant-seeming dynamic shardchain splitting/joining strategy probably based on the observation that a bit string is a binary tree address. That is a shardchain prefix just identifies a node somewhere in the tree. Splitting is just turning the two children into addresses (while retiring the parent's address) and merging is the reverse. In this way the system can "tune the tree" so that each node with an address (i.e. each shardchain) has an average transaction rate below some desired threshold. Was wondering how this compares to skycoins scaling plans.

**Comment by steady-clackin** [comment]
The hierarchy of master blockchain, workchains and shardchains outlined in the paper is also nice because shardchains belonging to different workchains can still message each other in a consensus-supported way. No examples come to mind, but I think such a feature could enable some interesting on-chain dapp architectures. Has they skycoin team made any technical plans about how to support on-chain dapp architectures?
