### ISSUE TITLE
Addresses should always be length 34 or 35

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#949]
Some addresses have less than 34 length, e.g. `n3E1TTLwZcmxu3CZpbEZbUT8eX4kQgujh`

Probably related to the base58 encoder. See #762 #763

**Comment by Senyoret1** [comment]
I think there is no problem. Since the addresses have 25 bytes, the maximum value could be ffffff..... That gives a number that can be divided 35 times by 58 (1606938044258990275541962092341162602522202993782792835301375), so the maximum length of the addresses is 35 characters. However, if the opposite is calculated, the smallest address that does not have leading zeros is 010000000...... That gives a number that can only be divided 33 times by 58 (6277101735386680763835789423207666416102355444464034512896). That means that the adress  with fewer characters and no leading zeros would have 33 characters, not 34.

However, if you take into account that the addresses can start with 0 and that Base 58 would place “1” for each leading zero, the smallest possible address would be 25 characters.

My calculations are simplistic, because do not take into account that the highest and the lowest numbers have checksums different than ffffffff and 00000000, but since the checksum is on the right, the variation in the calculations should not be very large. Someone did a calculation with bitcoin in which he found several addresses with 26 characters: https://bitcoin.stackexchange.com/a/36948

The example address (n3E1TTLwZcmxu3CZpbEZbUT8eX4kQgujh) has as public key hash 01ee0959c1ad899296812cb7a3b1069213d62cd0 Since it starts with 01, it is understandable that it has 33 characters.
