### ISSUE TITLE
docs and implementation of NewWallet and Wallet.GenerateAddresses need a review

### ISSUE THREAD

**Issue by mihis** [skycoin/skycoin#981]
While trying to use skycoin/services#6, with the seed, generated by skycoin/services#12, I have found following issues:

Docs for `wallet.NewWallet` claims that wallet generates a random seed if seed is "". Also it does not mention which encoding is expected.

However:

1. `wallet.NewWallet` returns error if seed is "" - https://github.com/skycoin/skycoin/blob/feaab10d4f951b8ffea53ef2d37a4cf5e3450b17/src/wallet/wallet.go#L80-L82

2.  `Wallet.GenerateAddresses` does not check for empty seed and on the first pass does not generate new one. Also, on the first pass it converts seed directly to byte representation, while the rest of the code assumes that seed is hex-encoded. 
https://github.com/skycoin/skycoin/blob/feaab10d4f951b8ffea53ef2d37a4cf5e3450b17/src/wallet/wallet.go#L212-L225

3. wallet.NewService uses bip39 to generate wallet's seed and does not encode it to hex.
https://github.com/skycoin/skycoin/blob/feaab10d4f951b8ffea53ef2d37a4cf5e3450b17/src/wallet/service.go#L52-L61

**Comment by gz-c** [comment]
@iketheadore this may affect wallets generated by 0.21.1

**Comment by iketheadore** [comment]
1. `NewWallet` used to generate bip39 random seed if it's empty, but was changed to return error in commit [4cf13727](https://github.com/skycoin/skycoin/commit/4cf13727825ac4989231fb6fae3388021789f273#diff-58ef2a3603aa69fc19f5a655823e7d94R75), @gz-c should we change back to generate random seed, or just update the doc.

2. We should check if seed is empty in `GenerateAddresses` method. 

3. We only encode the new seed that's derived from the initial seed by `cipher. GenerateDeterministicKeyPairsSeed` to hex, the returned new seed is `[]byte`, we encode it to hex string so that we can record it in the `wallet.meta`. We don't have to encode the initial seed to hex, it's already string type, and if we do, the wallet would break the be compatibility.

**Comment by gz-c** [comment]
1. update the doc, it no longer generates default seed
2. yes, check for empty seed in `GenerateAddresses`
3. I think this is a bigger problem, we use `[]byte(getLastSeed())` when `Entries` is 0 but use the decoded last seed otherwise, this will affect loading wallets from seed, it is possible to generate the wrong addresses.
